{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "aspnetservice.serviceAccountName" . }}
  labels:
{{ include "aspnetservice.labels" . | nindent 4 }}
{{- end -}}
